import { DialogConfig, DialogPreset } from './types';

export const DEFAULT_DIALOG_CONFIG: DialogConfig = {
  title: 'Confirm Operation',
  subtitle: 'Requires User Verification',
  badgeText: 'SECURITY VERIFIED',
  showBadge: true,
  headerId: 'erp-dialog-header',

  icon: 'warning',
  iconColor: '#F59E0B', // Amber 500
  iconBgColor: '#FEF3C7', // Amber 100
  iconAnimation: 'pulse',
  iconId: 'erp-dialog-icon',

  message: 'Are you sure you want to proceed with this action? This operation will affect live ledger data and cannot be automatically undone by the system.',
  detailedMessage: 'Stack Trace ID: ERR-ERP-2026-X841\nTransaction Timestamp: 2026-07-10T12:30:48-07:00\nDatabase Cluster: US-EAST-C1\nOperator Level: Tier 2 Financial Auditor',
  showDetails: false,
  affectedRecords: ['GL-LEDGER-ACC-1011', 'TXN-REF-98402'],
  bodyId: 'erp-dialog-body',

  confirmBtn: {
    text: 'Proceed Confirmation',
    variant: 'warning',
    show: true,
    disabled: false,
    loading: false,
    customId: 'erp-dialog-confirm-btn',
  },
  cancelBtn: {
    text: 'Abort Request',
    variant: 'outline',
    show: true,
    disabled: false,
    loading: false,
    customId: 'erp-dialog-cancel-btn',
  },
  auxBtn: {
    text: 'View Guidelines',
    variant: 'secondary',
    show: true,
    disabled: false,
    loading: false,
    customId: 'erp-dialog-aux-btn',
  },
  footerId: 'erp-dialog-footer',

  theme: 'dark',
  width: 'md',
  customWidth: '520px',
  zIndex: 1000,
  borderRadius: '16px',
  overlayOpacity: 0.65,
  overlayBlur: '6px',
  align: 'left',
  dialogId: 'erp-dialog-container',
  overlayId: 'erp-dialog-overlay',
  dir: 'ltr',

  animationType: 'scale',
  animationDuration: 300,
  animationEasing: 'ease-out',
};

export const DIALOG_PRESETS: DialogPreset[] = [
  {
    name: 'Critical Audit Deletion',
    description: 'Permanently remove transactional ledger data. High operational risk, dark red layout.',
    config: {
      title: 'Delete Ledger Transaction?',
      subtitle: 'Permanent Ledger Modification',
      badgeText: 'AUDIT RISK LEVEL 4',
      showBadge: true,
      icon: 'trash',
      iconColor: '#EF4444', // Red 500
      iconBgColor: '#FEE2E2', // Red 100
      iconAnimation: 'bounce',
      message: 'You are about to permanently purge ledger transaction record TXN-2026-8941. This action invalidates all linked ledger entries, creates an audit log gap, and dispatches a priority notification to your financial supervisor.',
      affectedRecords: [
        'GL-TXN-2026-8941 (Debit: $142,500.00)',
        'VAT-LEDGER-US-2026',
        'INVOICE-REF-9081',
      ],
      confirmBtn: {
        text: 'Confirm Ledger Purge',
        variant: 'danger',
        show: true,
        disabled: false,
        loading: false,
        customId: 'erp-dialog-confirm-btn',
      },
      cancelBtn: {
        text: 'Cancel and Retain',
        variant: 'outline',
        show: true,
        disabled: false,
        loading: false,
        customId: 'erp-dialog-cancel-btn',
      },
      auxBtn: {
        text: 'Audit Policy manual',
        variant: 'secondary',
        show: true,
        disabled: false,
        loading: false,
        customId: 'erp-dialog-aux-btn',
      },
      theme: 'dark',
      width: 'md',
      animationType: 'scale',
      animationDuration: 350,
      animationEasing: 'ease-out',
    },
  },
  {
    name: 'Price-Cap Override Warning',
    description: 'Manual transaction discount override. Medium risk, golden warning theme.',
    config: {
      title: 'Force Price-Cap Override',
      subtitle: 'Manual Discount Authorization Required',
      badgeText: 'AUTHORIZATION OVERRIDE',
      showBadge: true,
      icon: 'warning',
      iconColor: '#D97706', // Amber 600
      iconBgColor: '#FEF3C7',
      iconAnimation: 'pulse',
      message: 'The requested client discount (45%) exceeds the automated corporate cap of 25%. Proceeding requires registering an override incident report linked to your account.',
      affectedRecords: [
        'Quote #QT-9921 (Acme Corporation)',
        'Sales Representative: Sarah Jenkins',
        'Maximum Authorized Discount: 25%',
      ],
      confirmBtn: {
        text: 'Authorize Override',
        variant: 'warning',
        show: true,
        disabled: false,
        loading: false,
        customId: 'erp-dialog-confirm-btn',
      },
      cancelBtn: {
        text: 'Decline and Return',
        variant: 'outline',
        show: true,
        disabled: false,
        loading: false,
        customId: 'erp-dialog-cancel-btn',
      },
      auxBtn: {
        text: 'Review Delegation Matrix',
        variant: 'secondary',
        show: false,
        disabled: false,
        loading: false,
        customId: 'erp-dialog-aux-btn',
      },
      theme: 'amber',
      width: 'md',
      animationType: 'slide-up',
      animationDuration: 400,
    },
  },
  {
    name: 'Requisition Approval',
    description: 'Approve and release IT procurement budget. Green positive workflow.',
    config: {
      title: 'Approve Purchase Requisition',
      subtitle: 'Procurement Lifecycle Level 2',
      badgeText: 'FUNDS ALLOCATION APPROVED',
      showBadge: true,
      icon: 'check',
      iconColor: '#10B981', // Emerald 500
      iconBgColor: '#D1FAE5',
      iconAnimation: 'none',
      message: 'Approve purchase requisition REQ-55201. Clicking proceed releases $24,800.00 from the regional hardware budget and automatically files a purchase order with verified distributors.',
      affectedRecords: [
        'REQ-55201 (15x Developer Laptops)',
        'Release Target: Regional hardware IT budget',
        'Auto-Vendor: Dell Business Logistics',
      ],
      confirmBtn: {
        text: 'Approve & Release Funds',
        variant: 'success',
        show: true,
        disabled: false,
        loading: false,
        customId: 'erp-dialog-confirm-btn',
      },
      cancelBtn: {
        text: 'Reject Requisition',
        variant: 'outline',
        show: true,
        disabled: false,
        loading: false,
        customId: 'erp-dialog-cancel-btn',
      },
      auxBtn: {
        text: 'Edit Requisition first',
        variant: 'secondary',
        show: true,
        disabled: false,
        loading: false,
        customId: 'erp-dialog-aux-btn',
      },
      theme: 'light',
      width: 'md',
      animationType: 'slide-down',
      animationDuration: 250,
    },
  },
  {
    name: 'Background Data Export',
    description: 'Compile and download massive spreadsheet archives. Slate theme.',
    config: {
      title: 'Export Consolidated Balances?',
      subtitle: 'Q2 2026 Audit Consolidation Ledger',
      badgeText: 'SYSTEM EXPORT SERVICE',
      showBadge: true,
      icon: 'info',
      iconColor: '#3B82F6', // Blue 500
      iconBgColor: '#DBEAFE',
      iconAnimation: 'none',
      message: 'Initiate general ledger data extraction. This compiler sweeps over 12 global subsidiaries to aggregate currency fluctuations. Completion triggers a secure background download.',
      affectedRecords: [
        'Aggregated ledger accounts: 140',
        'Projected compilation time: ~45 seconds',
        'Target format: Excel workbook (.xlsx)',
      ],
      confirmBtn: {
        text: 'Execute Ledger Compilation',
        variant: 'primary',
        show: true,
        disabled: false,
        loading: false,
        customId: 'erp-dialog-confirm-btn',
      },
      cancelBtn: {
        text: 'Dismiss',
        variant: 'outline',
        show: true,
        disabled: false,
        loading: false,
        customId: 'erp-dialog-cancel-btn',
      },
      auxBtn: {
        text: 'Configure Columns',
        variant: 'secondary',
        show: true,
        disabled: false,
        loading: false,
        customId: 'erp-dialog-aux-btn',
      },
      theme: 'slate',
      width: 'lg',
      animationType: 'fade',
      animationDuration: 300,
    },
  },
  {
    name: 'حذف فاتورة مبيعات (RTL Arabic)',
    description: 'طلب حذف فاتورة مبيعات معتمدة من النظام. يدعم اتجاه اليمين لليسار بالكامل.',
    config: {
      title: 'حذف فاتورة مبيعات؟',
      subtitle: 'تعديل سجلات المبيعات والضرائب المعتمدة',
      badgeText: 'خطورة تدقيق قصوى',
      showBadge: true,
      icon: 'trash',
      iconColor: '#EF4444',
      iconBgColor: '#FEE2E2',
      iconAnimation: 'bounce',
      message: 'أنت على وشك حذف فاتورة مبيعات معتمدة برقم INV-2026-0041 نهائياً. سيؤدي هذا الإجراء إلى إلغاء جميع قيود اليومية المرتبطة، وتنبيه الإدارة المالية، وتوليد فجوة في تدقيق ضريبة القيمة المضافة.',
      affectedRecords: [
        'فاتورة مبيعات INV-2026-0041 (القيمة: 142,500.00 ر.س)',
        'قيد اليومية JV-SL-9021 (دائن/مدين)',
        'سجل إقرارات ضريبة القيمة المضافة للربع الثاني 2026'
      ],
      confirmBtn: {
        text: 'تأكيد الحذف نهائياً',
        variant: 'danger',
        show: true,
        disabled: false,
        loading: false,
        customId: 'erp-dialog-confirm-btn',
      },
      cancelBtn: {
        text: 'إلغاء والاحتفاظ بالفاتورة',
        variant: 'outline',
        show: true,
        disabled: false,
        loading: false,
        customId: 'erp-dialog-cancel-btn',
      },
      auxBtn: {
        text: 'سياسة التدقيق المالي',
        variant: 'secondary',
        show: true,
        disabled: false,
        loading: false,
        customId: 'erp-dialog-aux-btn',
      },
      theme: 'dark',
      width: 'md',
      align: 'left',
      dir: 'rtl',
      animationType: 'scale',
      animationDuration: 350,
    },
  },
];
